require.config({
	baseUrl:"/js/",
	paths:{
		"mui":"libs/mui.min",
		"picker":"libs/mui.picker.min",
		"poppicker":"libs/mui.poppicker",
		"format":"common/format",
		"getuser":'common/getuser'
	},
	shim:{
		"picker":{deps:['mui']},
		"poppicker":{deps:['mui']}
	}
})