require.config({
	baseUrl:"/js/",
	paths:{
		"mui":"libs/mui.min",
		"picker":"libs/mui.picker.min",
		"poppicker":"libs/mui.poppicker",
		"format":"common/format", 
		"getuser":'common/getuser',
		"getParams":'common/getParams',
		"moment":"libs/moment.min"
	},
	shim:{
		"picker":{deps:['mui']},
		"poppicker":{deps:['mui']}
	}
})